development:
  server: "http://localhost:9292/faye/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye/faye"
  secret_token: "secret"
production:
  server: "https://test-server-2.herokuapp.com/faye"
  secret_token: "vivelafrance"
